

set tabstop=8
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab
set autoindent

set ignorecase
set smartcase

set mouse=""
set hidden
set number
"set cursorline
set nocursorline
set termguicolors
set history=300
set cmdheight=2 "The commandbar height
set ls=2        "always show filename
set showcmd	" Show (partial) command in status line.
set showmatch   " Show matching bracets when text indicator is over them
set mat=2       " How many tenths of a second to blink
set pumheight=5 " Limit popup menu height 
set completeopt=menuone,longest

"set autochdir	" automatically change window's cwd to file's dir
set autoread 	" Set to auto read when a file is changed from the outside
set autowrite	" Automatically save before commands like :next and :make

" Turn backup off and undo file
set nobackup
set noswapfile
set noundofile

set wildmenu
"set wildmode=list:longest,full
set wildmode=longest:list,full

set wildignorecase
set wildignore=*.swp,*.bak
set wildignore+=*.pyc,*.class,*.sln,*.Master,*.csproj,*.csproj.user,*.cache,*.dll,*.pdb,*.min.*
set wildignore+=*/.git/**/*,*/.hg/**/*,*/.svn/**/*
set wildignore+=tags
set wildignore+=*.tar.*

set omnifunc=syntaxcomplete#Complete

set dictionary=/usr/share/dict/words
" set complete+=k "the word completion will also use dictionary

set path+=**



set statusline=
set statusline+=%<%F                                    "show full file path 
set statusline+=%m%r%h                                  "modified, read-only, help-file
set statusline+=%=%y                                    "file type
set statusline+=[%{strlen(&fenc)?&fenc:'none'},%{&ff}]  "encoding, file-format
set statusline+=\ %c\ %l/%L\ %P                         "column, line, file length, file percent


nnoremap <C-l> :nohl<CR><C-l>
nnoremap gb :ls<CR>:b<Space>


colorscheme desert
filetype indent plugin on
syntax enable

